<?php
class SpecialChars {
    private static $mapping = [
        '’' => "'",
        "“" => '(',
        "”" => ')',
        "\xE2\x80\x90" => '-',   // U+2010 hyphen
        "\xE2\x80\x91" => '-',   // U+2011 non-breaking hyphen
        "\xE2\x80\x92" => '-',   // U+2012 figure dash
        "\xE2\x80\x93" => '-',   // U+2013 en dash
        "\xE2\x80\x94" => '-',   // U+2014 em dash
        "\xE2\x80\x95" => '-',   // U+2015 horizontal bar
        "\xE2\x88\x92" => '-',   // U+2212 minus sign
        'Ã' => "A'",
        'Ã¡' => "a'",
        'Ã©' => "e'",
        'Ã³' => "o'",
        'Ãº' => "u'",
        'Ã±' => "n~",
        'Ã§' => "c--",
        'Ã£' => "a~",
        'Ãµ' => "o~",
        'Ãª' => "e^",
        "Ã¯" => "i:",
        'Ã´' => "o^",
        'Ã¼' => 'u:',
        'Ã¶' => 'o:',
        'Ã«' => 'e:',
        'Ãœ' => 'U:',
        'Ã“' => "O'",
        "Â " => ' ',
        "\xC3\xAD" => "i'",
        'Ã' => 'i',
        'Å‚' => 'l/',
        'Å' => 'L/',
        'Å„' => 'n~',
        'Å»' => 'Z.',
        'Åº' => "z'",
        'Å›' => "s'",
        'Å¼' => "z.",
        'Ä™' => "e--",
        'Ä…' => 'ą',
        'Ä‡' => "c'",
        'Ä°' => 'I.',
        'Å ' => 'S^',
        'Å¡' => 's^',
        'Ä' => 'c^',
        'ÅŸ' => 's--',
        " \xC2\xA0" => ' ',
        "\xC2\xA0" => ' ',
        "\xC2\xAD" => '',   // soft hyphen U+00AD
        "Â" => '',   // orphaned Â (mojibake from corrupted nbsp)
        "â€™" => "''",
        'Ìƒ' => '~',    // on prev character
        'Ì' => '`',    // on prev character
        'Ì§' => '--',    // on prev character
    "Ä"=>'A:',    // don't do because it's utf
    "ä"=>'a:',
    "À"=>"A`",    // grave
    "à"=>"a`",
    "Á"=>"A'",    // acute
    "á"=>"a'",
    // "Â"=>'A^',  // disabled: standalone Â is almost always mojibake (corrupted nbsp etc.,
                    // see "Â " and "Â" rules above), not a real A-circumflex; enabling this
                    // would silently miscode leftover mojibake as A^ instead of leaving it visible
    "â"=>'a^',
    "ã"=>'a~',
    "Å"=>'A@', 
    "å"=>'a@',
    "Ă"=>'A*',
    "ă"=>'a*',    // a-brev
    "ā"=>'a_',
    "Ā"=>'A_',
    "Ą"=>"A--",
    "ą"=>"a--",
    "Ç"=>'C--',   // c,
    "ç"=>'c--',   // c,
    "Č"=>'C^',
    "č"=>'c^',
    "Ć"=>"C'",
    "ć"=>"c'",
    "Đ"=>'D---',   // vietnamese upper case eth
    "đ"=>'d---',   // vietnamese lower case eth
    "Ð"=>'D--',   // danish upper case eth
    "ð"=>'d--',   // danish lower case eth
    "Ë"=>'E:', 
    "ë"=>'e:', 
    "È"=>"E`",    // grave
    "è"=>"e`",
    "É"=>"E'",    // acute
    "é"=>"e'",
    "ě"=>"e^",
    "Ė"=>'E.',
    "ė"=>'e.',
    "ē"=>'e_',
    "Ē"=>'E_',
    'ę'=>'e--',
    'Ę'=>'E--',
    "Ğ"=>"G^",    // turkish soft g
    "ğ"=>"g^",
    "Ì"=>"I`",    // grave
    "ì"=>"i`",
    "Í"=>"I'",    // acute
    "í"=>"i'",
    "İ"=>"I.",
    "ı"=>'i.',
    "ī"=>'i_',
    "Ī"=>'I_',
    "Ï"=>'I:',
    "ï"=>'i:',
    "Ł"=>"L/",
    "ł"=>"l/",
    "Ľ"=>"L''",
    "ľ"=>"l''",
    "Ñ"=>'N~',
    "ñ"=>'n~',
    "ń"=>"n'",    // acute (Polish ń)
    "Ň"=>"N^",
    "ň"=>"n^",
    "Ò"=>"O`",    // grave (Hungarian)
    "ò"=>"o`",    // grave
    "Ó"=>"O''",   // acute
    "ó"=>"o''",   // acute
    "ô"=>'o^', 
    "Õ"=>"O~",
    "õ"=>'o~',
    "Ö"=>'O:', 
    "ö"=>'o:', 
    "Ø"=>'O/', 
    "ø"=>'o/', 
    "Ř"=>'R^',
    "ř"=>'r^',
    "Ś"=>"S'",
    "ś"=>"s'",
    "Ş"=>'S--',   // S,
    "ş"=>'s--',   // s,
    "Š"=>'S^',
    "š"=>'s^',
    "ß"=>'s*',    // german s-set
    "Ť"=>'T^',
    "ť"=>'t^',
    "Ţ"=>'T--',
    "ţ"=>'t--',
    "Ț"=>'T---',
    "ț"=>'t---',
    "Û"=>'U^',
    "û"=>'u^', 
    "Ü"=>'U:', 
    "ü"=>'u:', 
    "ů"=>'u@',    // u ring
    "Ū"=>'U_',
    "ū"=>'u_',
    "Ú"=>"U'",
    "ú"=>"u'",
    "ÿ"=>'y:',
    "Ÿ"=>'Y:',
    "Ý"=>"Y'",
    "ý"=>"y'",
    "Ž"=>'Z^',
    "ž"=>'z^',
    "Ż"=>'Z.',
    "ż"=>"z.",
    "ź"=>"z'",
  ];

  static function replace(string $str): string {
    static $keys = null, $values = null;
    if ($keys === null) {
      $keys = array_keys(self::$mapping);
      $values = array_values(self::$mapping);
    }
    return str_replace($keys, $values, $str);
  }
}