import json, os

path = os.path.expanduser("~/workspace/musmem/data/contest_locations.json")

with open(path) as f:
    data = json.load(f)

# New entries extracted from article scraping (sessions 1-2, files 1-50)
new_entries = [
    # --- Page 46 (2019 contests) ---
    {"contest": "Romania Muscle Fest Pro - IFBB", "year": "2019",
     "date": "November 3, 2019", "location": "Bucharest, Romania"},
    {"contest": "Ultimate Warriors Pro - IFBB", "year": "2019",
     "date": "November 2, 2019", "location": "San Diego, California, USA"},
    {"contest": "Sacramento Pro - IFBB", "year": "2019",
     "date": "November 2, 2019", "location": "Sacramento, California, USA"},
    {"contest": "Baltimore Pro - IFBB", "year": "2019",
     "date": "October 26, 2019", "location": "Baltimore, Maryland, USA"},
    {"contest": "Titans Grand Prix Pro - IFBB", "year": "2019",
     "date": "October 19, 2019", "location": "Los Angeles, California, USA"},
    {"contest": "San Antonio Classic Pro - IFBB", "year": "2019",
     "date": "October 19, 2019", "location": "San Antonio, Texas, USA"},
    {"contest": "Kentucky Muscle Pro - IFBB", "year": "2019",
     "date": "October 19, 2019", "location": "Louisville, Kentucky, USA"},
    {"contest": "Monterrey Pro - IFBB", "year": "2019",
     "date": "October 5, 2019", "location": "Monterrey, Nuevo León, Mexico"},
    {"contest": "Powerhouse Classic Pro - IFBB", "year": "2019",
     "date": "September 28, 2019", "location": "Ypsilanti, Michigan, USA"},
    {"contest": "Asia Grand Prix - IFBB", "year": "2019",
     "date": "September 22, 2019", "location": "Incheon, South Korea"},
    # --- Page 45 (2019 contests) ---
    {"contest": "Battle of Texas Pro - IFBB", "year": "2019",
     "date": "December 14, 2019", "location": "Dallas, Texas, USA"},
    {"contest": "Legion Sports Fest Pro - IFBB", "year": "2019",
     "date": "November 10, 2019", "location": "Long Beach, California, USA"},
    # --- Page 44 (2020 contests) ---
    {"contest": "Pacific USA Pro - IFBB", "year": "2020",
     "date": "August 27, 2020", "location": "San Diego, California, USA"},
    {"contest": "Optimum Classic Pro - IFBB", "year": "2020",
     "date": "August 29, 2020", "location": "Shreveport, Louisiana, USA"},
    {"contest": "Tampa Pro - IFBB", "year": "2020",
     "date": "July 31-August 1, 2020", "location": "Tampa, Florida, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2020",
     "date": "July 18, 2020", "location": "Omaha, Nebraska, USA"},
    {"contest": "Wasatch Warrior Pro - IFBB", "year": "2020",
     "date": "July 11, 2020", "location": "Salt Lake City, Utah, USA"},
    {"contest": "Northern California Pro - IFBB", "year": "2020",
     "date": "July 11, 2020", "location": "Sacramento, California, USA"},
    # --- Page 43 (2020 contests) ---
    {"contest": "Minneapolis Pro - IFBB", "year": "2020",
     "date": "October 3, 2020", "location": "Minneapolis, Minnesota, USA"},
    {"contest": "Tahoe Pro - IFBB", "year": "2020",
     "date": "September 27, 2020", "location": "Squaw Valley, California, USA"},
    {"contest": "California State Pro - IFBB", "year": "2020",
     "date": "September 12, 2020", "location": "Las Vegas, Nevada, USA"},
    {"contest": "New York Pro Championships - IFBB", "year": "2020",
     "date": "September 5, 2020", "location": "Tampa, Florida, USA"},
    {"contest": "Pittsburgh Pro - IFBB", "year": "2020",
     "date": "September 2, 2020", "location": "Pittsburgh, Pennsylvania, USA"},
    # --- Page 42 (2020 contests) ---
    {"contest": "MuscleContest Nacional Pro - IFBB", "year": "2020",
     "date": "November 8, 2020", "location": "Sao Paulo, Brazil"},
    {"contest": "San Antonio Pro - IFBB", "year": "2020",
     "date": "November 7, 2020", "location": "San Antonio, Texas, USA"},
    {"contest": "Sacramento Pro - IFBB", "year": "2020",
     "date": "October 17, 2020", "location": "Sacramento, California, USA"},
    # --- Page 41 (2021/2020 contests) ---
    {"contest": "Wasatch Warrior Pro - IFBB", "year": "2021",
     "date": "April 17, 2021", "location": "Salt Lake City, Utah, USA"},
    {"contest": "World Klash Pro - IFBB", "year": "2021",
     "date": "April 3, 2021", "location": "Orlando, Florida, USA"},
    {"contest": "USA Championships - NPC", "year": "2020",
     "date": "December 13-14, 2020", "location": "Phoenix, Arizona, USA"},
    {"contest": "Battle of Texas Pro - IFBB", "year": "2020",
     "date": "December 4-5, 2020", "location": "Dallas, Texas, USA"},
    {"contest": "Atlantic Coast Pro - IFBB", "year": "2020",
     "date": "November 28, 2020", "location": "Fort Lauderdale, Florida, USA"},
    # --- Page 40 (2021 contests) ---
    {"contest": "Mile High Pro - IFBB", "year": "2021",
     "date": "June 5, 2021", "location": "Denver, Colorado, USA"},
    {"contest": "California State Pro - IFBB", "year": "2021",
     "date": "May 29, 2021", "location": "San Diego, California, USA"},
    {"contest": "Optimum Classic Pro - IFBB", "year": "2021",
     "date": "May 22, 2021", "location": "Shreveport, Louisiana, USA"},
    {"contest": "New York Pro Championships - IFBB", "year": "2021",
     "date": "May 15, 2021", "location": "Tampa, Florida, USA"},
    {"contest": "Junior USA Championships - NPC", "year": "2021",
     "date": "May 13, 2021"},
    {"contest": "St. Louis Pro - IFBB", "year": "2021",
     "date": "May 8, 2021", "location": "St. Louis, Missouri, USA"},
    {"contest": "GRL PWR Pro - IFBB", "year": "2021",
     "date": "May 8, 2021", "location": "Orlando, Florida, USA"},
    {"contest": "Indy Pro - IFBB", "year": "2021",
     "date": "May 8, 2021", "location": "Indianapolis, Indiana, USA"},
    {"contest": "Pittsburgh Pro - IFBB", "year": "2021",
     "date": "April 30-May 1, 2021", "location": "Pittsburgh, Pennsylvania, USA"},
    # --- Page 39 (2021 contests) ---
    {"contest": "Universe - NPC", "year": "2021",
     "date": "July 1-3, 2021"},
    {"contest": "Puerto Rico Pro - IFBB", "year": "2021",
     "date": "June 26-27, 2021", "location": "Nassau, Bahamas"},
    {"contest": "DC Pro - IFBB", "year": "2021",
     "date": "June 19, 2021", "location": "Herndon, Virginia, USA"},
    {"contest": "Northern California Pro - IFBB", "year": "2021",
     "date": "June 12, 2021", "location": "Sacramento, California, USA"},
    {"contest": "Clash at the Titanz Pro - IFBB", "year": "2021",
     "date": "June 12, 2021", "location": "Austell, Georgia, USA"},
    {"contest": "Miami Muscle Beach Pro - IFBB", "year": "2021",
     "date": "June 5, 2021", "location": "Miami Beach, Florida, USA"},
    # --- Page 38 (2021 contests) ---
    {"contest": "Republic of Texas Pro - IFBB", "year": "2021",
     "date": "July 17, 2021", "location": "Austin, Texas, USA"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2021",
     "date": "July 10, 2021", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2021",
     "date": "July 10, 2021", "location": "Omaha, Nebraska, USA"},
    # --- Session 1: files 1-24 ---
    # Mr America - AAU 1945: already complete in JSON, skip
    # Mr America - AAU 1946: date already in JSON, fill venue/location
    {"contest": "Mr America - AAU", "year": "1946",
     "venue": "Boys' Club", "location": "Detroit, Michigan, USA"},
    {"contest": "Mr America - AAU", "year": "1947",
     "date": "June 28-29, 1947", "venue": "Lane Tech High School Auditorium",
     "location": "Chicago, Illinois, USA"},
    {"contest": "Mr America - AAU", "year": "1948",
     "location": "Los Angeles, California, USA"},
    {"contest": "Mr America - AAU", "year": "1951",
     "date": "June 15-16, 1951", "venue": "Greek Theatre, Griffith Park",
     "location": "Los Angeles, California, USA"},
    {"contest": "Mr America - AAU", "year": "1952",
     "date": "June 27-28, 1952", "location": "New York City, New York, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1952",
     "date": "July 12, 1952", "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1953",
     "date": "June 5-6, 1953", "venue": "Murat Theater",
     "location": "Indianapolis, Indiana, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1954",
     "date": "June 25-26, 1954", "venue": "Scala Theatre",
     "location": "London, England, UK"},
    # Mr America - AAU 1954: existing JSON has "June 26-27, 1954" — possible conflict, include to detect
    {"contest": "Mr America - AAU", "year": "1954",
     "date": "June 25-26, 1954", "venue": "Greek Theatre",
     "location": "Los Angeles, California, USA"},
    {"contest": "Mr America - AAU", "year": "1955",
     "date": "June 4-5, 1955", "venue": "Masonic Auditorium",
     "location": "Cleveland, Ohio, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1955",
     "date": "June 11, 1955", "venue": "London Palladium",
     "location": "London, England, UK"},
    # --- Session 2: files 25-50 ---
    {"contest": "Mr Universe - NABBA", "year": "1956",
     "venue": "London Palladium", "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1957",
     "venue": "Peabody Auditorium", "location": "Daytona Beach, Florida, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1957",
     "date": "October 19, 1957", "venue": "London Coliseum",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1957",
     "date": "October 19, 1957", "venue": "London Coliseum",
     "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1958",
     "venue": "Embassy Auditorium", "location": "Los Angeles, California, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1958",
     "venue": "London Coliseum", "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1958",
     "venue": "London Coliseum", "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1959",
     "date": "July 31 - August 1, 1959", "venue": "York Fair Grounds",
     "location": "York, Pennsylvania, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1959",
     "venue": "London Palladium", "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1959",
     "venue": "London Palladium", "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1960",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1960",
     "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1961",
     "venue": "Santa Monica Civic Auditorium",
     "location": "Santa Monica, California, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1961",
     "venue": "Victoria Palace Theatre", "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1961",
     "venue": "Victoria Palace Theatre", "location": "London, England, UK"},
    {"contest": "Mr America - AAU", "year": "1962",
     "location": "Detroit, Michigan, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1962",
     "date": "September 29, 1962", "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1962",
     "date": "September 29, 1962", "location": "London, England, UK"},
    {"contest": "Junior Mr America - AAU", "year": "1963",
     "date": "June 1, 1963", "venue": "Jefferson High School Auditorium",
     "location": "Columbia, Missouri, USA"},
    {"contest": "Mr America - AAU", "year": "1964",
     "date": "June 13-14, 1964", "location": "Chicago, Illinois, USA"},
    {"contest": "Mr Universe - NABBA", "year": "1964",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1964",
     "location": "London, England, UK"},
    {"contest": "Mr America - IFBB", "year": "1964",
     "date": "September 19, 1964", "venue": "Brooklyn Academy of Music",
     "location": "New York City, New York, USA"},
    {"contest": "Universe - IFBB", "year": "1964",
     "date": "September 19, 1964", "venue": "Brooklyn Academy of Music",
     "location": "New York City, New York, USA"},
    # --- Session 3: files 51-100 ---
    # Mr America - AAU 1956 (mb560821.xml)
    {"contest": "Mr America - AAU", "year": "1956",
     "date": "June 1-2, 1956", "venue": "University of Pennsylvania Palestra",
     "location": "Philadelphia, Pennsylvania, USA"},
    # Mr America - AAU 1962 update — more specific than stored "Detroit, Michigan, USA"
    # (may produce CONFLICT on location; venue and date are new data)
    {"contest": "Mr America - AAU", "year": "1962",
     "date": "June 2-3, 1962", "venue": "Highland Park High School Auditorium",
     "location": "Highland Park, Michigan, USA"},
    # Mr America - AAU 1965-1968 (im24069, im250638, im260614, im270634)
    {"contest": "Mr America - AAU", "year": "1965",
     "date": "June 11-12, 1965", "venue": "Embassy Auditorium",
     "location": "Los Angeles, California, USA"},
    {"contest": "Mr America - AAU", "year": "1966",
     "location": "York, Pennsylvania, USA"},
    {"contest": "Mr America - AAU", "year": "1967",
     "location": "Columbus, Ohio, USA"},
    {"contest": "Mr America - AAU", "year": "1968",
     "location": "Columbus, Ohio, USA"},
    # Junior Mr America - AAU 1955 (mb550822.xml — same event as Mr America)
    {"contest": "Junior Mr America - AAU", "year": "1955",
     "date": "June 4, 1955", "venue": "Masonic Temple",
     "location": "Cleveland, Ohio, USA"},
    # Junior Mr America - AAU 1965-1966 (im250628, im250638)
    {"contest": "Junior Mr America - AAU", "year": "1965",
     "date": "June 11-12, 1965", "venue": "Embassy Auditorium",
     "location": "Los Angeles, California, USA"},
    {"contest": "Junior Mr America - AAU", "year": "1966",
     "date": "May 28-29, 1966", "venue": "San Jose Civic Auditorium",
     "location": "San Jose, California, USA"},
    # Mr Universe - NABBA 1956 date update (mb561111.xml) + 1965-1968 (im/ files)
    {"contest": "Mr Universe - NABBA", "year": "1956",
     "date": "June 15-16, 1956", "venue": "London Palladium",
     "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1965",
     "date": "September 25, 1965", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1966",
     "date": "September 23-24, 1966", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1967",
     "date": "September 23, 1967", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1968",
     "date": "September 21, 1968", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    # Universe - Pro - NABBA 1956 (mb561111.xml) + 1965-1968 (im/ files)
    {"contest": "Universe - Pro - NABBA", "year": "1956",
     "date": "June 15-16, 1956", "venue": "London Palladium",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1965",
     "date": "September 25, 1965", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1966",
     "date": "September 23-24, 1966", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1967",
     "date": "September 23, 1967", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1968",
     "date": "September 21, 1968", "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    # Mr America - IFBB 1962, 1965-1967 (ma050846, im250218, im260214 via ma2, im270120)
    {"contest": "Mr America - IFBB", "year": "1962",
     "date": "September 15, 1962", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr America - IFBB", "year": "1965",
     "date": "September 18, 1965", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr America - IFBB", "year": "1966",
     "date": "September 17, 1966", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr America - IFBB", "year": "1967",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # Universe - IFBB 1962, 1965-1966 (same shows as Mr America IFBB)
    {"contest": "Universe - IFBB", "year": "1962",
     "date": "September 15, 1962", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Universe - IFBB", "year": "1965",
     "date": "September 18, 1965", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Universe - IFBB", "year": "1966",
     "date": "September 17, 1966", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # Olympia - IFBB 1965-1967, 1969 (ma110478, im250218, im260214 via ma2, im270120)
    {"contest": "Olympia - IFBB", "year": "1965",
     "date": "September 18, 1965", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Olympia - IFBB", "year": "1966",
     "date": "September 17, 1966", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Olympia - IFBB", "year": "1967",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Olympia - IFBB", "year": "1969",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # Mr World - IFBB 1966-1967 (im260214 via ma2, im270120)
    {"contest": "Mr World - IFBB", "year": "1966",
     "date": "September 17, 1966", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr World - IFBB", "year": "1967",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # --- Session 4: files 101-150 ---
    # mb610325.xml: 1960 IFBB shows at Monument-National, Montreal (event link confirmed)
    {"contest": "Mr America - IFBB", "year": "1960",
     "date": "October 2, 1960", "venue": "Monument-National",
     "location": "Montreal, Quebec, Canada"},
    {"contest": "Universe - IFBB", "year": "1960",
     "date": "October 2, 1960", "venue": "Monument-National",
     "location": "Montreal, Quebec, Canada"},
    # mb640312.xml: 1963 IFBB shows at Brooklyn Academy of Music (event links confirmed)
    {"contest": "Mr America - IFBB", "year": "1963",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Universe - IFBB", "year": "1963",
     "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # mb700440.xml: 1969 NABBA Universe (London, no venue/date)
    {"contest": "Mr Universe - NABBA", "year": "1969",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1969",
     "location": "London, England, UK"},
    # mb710552.xml: 1970 NABBA Universe (London, no venue/date)
    {"contest": "Mr Universe - NABBA", "year": "1970",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1970",
     "location": "London, England, UK"},
    # mb701024.xml: 1970 IFBB Mr. World in Belgium (October 12, no city)
    {"contest": "Mr World - IFBB", "year": "1970",
     "date": "October 12, 1970", "location": "Belgium"},
    # mb710719.xml: 1970 Olympia at Town Hall, New York (no specific date in article)
    {"contest": "Olympia - IFBB", "year": "1970",
     "venue": "Town Hall", "location": "New York, New York, USA"},
    # mb711275.xml: 1971 IFBB Mr. America at Aquarius Theatre, Hollywood
    {"contest": "Mr America - IFBB", "year": "1971",
     "venue": "Aquarius Theatre",
     "location": "Hollywood, California, USA"},
    # mb720424.xml: 1971 IFBB Universe + Olympia at Palais de la Mutualité, Paris
    # (pre-judging Sept 24, formal contest Sept 25)
    {"contest": "Universe - IFBB", "year": "1971",
     "date": "September 24-25, 1971", "venue": "Palais de la Mutualité",
     "location": "Paris, France"},
    {"contest": "Olympia - IFBB", "year": "1971",
     "date": "September 25, 1971", "venue": "Palais de la Mutualité",
     "location": "Paris, France"},
    # mb720619.xml: 1971 IFBB Mr. World at White Plains County Center, Sept 12
    {"contest": "Mr World - IFBB", "year": "1971",
     "date": "September 12, 1971", "venue": "White Plains County Center",
     "location": "White Plains, New York, USA"},
    # mb730524.xml: 1972 IFBB Mr. America + Mr. World at BAM, Sept 16
    {"contest": "Mr America - IFBB", "year": "1972",
     "date": "September 16, 1972", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr World - IFBB", "year": "1972",
     "date": "September 16, 1972", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # mb730739.xml: 1972 IFBB Universe at Al-Nasr Cinema, Baghdad, Nov 21
    {"contest": "Universe - IFBB", "year": "1972",
     "date": "November 21, 1972", "venue": "Al-Nasr Cinema",
     "location": "Baghdad, Iraq"},
    # mb740129.xml / mb740524.xml: 1973 IFBB Mr. America + Mr. World + Olympia at BAM, Sept 8
    {"contest": "Mr America - IFBB", "year": "1973",
     "date": "September 8, 1973", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Mr World - IFBB", "year": "1973",
     "date": "September 8, 1973", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    {"contest": "Olympia - IFBB", "year": "1973",
     "date": "September 8, 1973", "venue": "Brooklyn Academy of Music",
     "location": "Brooklyn, New York, USA"},
    # mb740724.xml: 1973 IFBB Universe at Victoria Hall, Geneva, Oct 20
    {"contest": "Universe - IFBB", "year": "1973",
     "date": "October 20, 1973", "venue": "Victoria Hall",
     "location": "Geneva, Switzerland"},
    # mb750328.xml: 1974 IFBB Mr. America + Mr. World + Olympia at Felt Forum, Oct 12
    {"contest": "Mr America - IFBB", "year": "1974",
     "date": "October 12, 1974", "venue": "Felt Forum",
     "location": "New York, New York, USA"},
    {"contest": "Mr World - IFBB", "year": "1974",
     "date": "October 12, 1974", "venue": "Felt Forum",
     "location": "New York, New York, USA"},
    {"contest": "Olympia - IFBB", "year": "1974",
     "date": "October 12, 1974", "venue": "Felt Forum",
     "location": "New York, New York, USA"},
    # mb750528.xml: 1974 IFBB Universe at Teatro Nuovo, Verona, Oct 3-6
    {"contest": "Universe - IFBB", "year": "1974",
     "date": "October 3-6, 1974", "venue": "Teatro Nuovo",
     "location": "Verona, Italy"},
    # mb751112.xml: 1975 AAU Mr. America at Culver City Veterans Memorial Auditorium, June 19
    {"contest": "Mr America - AAU", "year": "1975",
     "date": "June 19, 1975", "venue": "Culver City Veterans Memorial Auditorium",
     "location": "Culver City, California, USA"},
    # --- Session 5: files 151-200 ---
    # md010226.xml: 1963 NABBA Mr. Universe at Victoria Palace Theatre, London
    {"contest": "Mr Universe - NABBA", "year": "1963",
     "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1963",
     "venue": "Victoria Palace Theatre",
     "location": "London, England, UK"},
    # md061032.xml: 1969 AAU Mr. America at DePaul Alumni Hall, Chicago, June 13-15
    {"contest": "Mr America - AAU", "year": "1969",
     "date": "June 13-15, 1969", "venue": "Alumni Hall, DePaul University",
     "location": "Chicago, Illinois, USA"},
    # md070932.xml: 1970 AAU Mr. America at Veterans Memorial Auditorium, Culver City, June 14
    {"contest": "Mr America - AAU", "year": "1970",
     "date": "June 14, 1970", "venue": "Veterans Memorial Auditorium",
     "location": "Culver City, California, USA"},
    # md070822.xml: 1970 Junior Mr. America at Brentwood, NY, May 17
    {"contest": "Junior Mr America - AAU", "year": "1970",
     "date": "May 17, 1970",
     "location": "Brentwood, New York, USA"},
    # md08098.xml: 1971 AAU Mr. America at York, PA, June 12
    # (also confirms Junior Mr. America AAU 1971 in Baytown, TX, May 16)
    {"contest": "Mr America - AAU", "year": "1971",
     "date": "June 12, 1971",
     "location": "York, Pennsylvania, USA"},
    {"contest": "Junior Mr America - AAU", "year": "1971",
     "date": "May 16, 1971",
     "location": "Baytown, Texas, USA"},
    # md09098.xml: 1972 AAU Mr. America at Masonic Temple, Detroit
    {"contest": "Mr America - AAU", "year": "1972",
     "venue": "Masonic Temple",
     "location": "Detroit, Michigan, USA"},
    # mb761164.xml: 1976 AAU Mr. America in Philadelphia (no venue or date in article)
    {"contest": "Mr America - AAU", "year": "1976",
     "location": "Philadelphia, Pennsylvania, USA"},
    # mb760441.xml / mb760243.xml: 1975 IFBB Mr. World at Felt Forum (MSG), Sept 27
    {"contest": "Mr World - IFBB", "year": "1975",
     "date": "September 27, 1975", "venue": "Felt Forum",
     "location": "New York, New York, USA"},
    # mb760417.xml: 1975 IFBB Universe + Olympia at University of South Africa, Pretoria, Nov 7-8
    {"contest": "Universe - IFBB", "year": "1975",
     "date": "November 7-8, 1975", "venue": "University of South Africa",
     "location": "Pretoria, South Africa"},
    {"contest": "Olympia - IFBB", "year": "1975",
     "date": "November 7-8, 1975", "venue": "University of South Africa",
     "location": "Pretoria, South Africa"},
    # mb761241.xml / mb761244.xml: 1976 Olympia at Veterans Memorial Auditorium, Columbus, Sept 18
    {"contest": "Olympia - IFBB", "year": "1976",
     "date": "September 18, 1976", "venue": "Veterans Memorial Auditorium",
     "location": "Columbus, Ohio, USA"},
    # --- Session 6: files 201-250 ---
    # mp080350.xml: 1949 AAU Mr. America at Masonic Auditorium, Cleveland, May 21-22
    {"contest": "Mr America - AAU", "year": "1949",
     "date": "May 21-22, 1949", "venue": "Masonic Auditorium",
     "location": "Cleveland, Ohio, USA"},
    # mp200825.xml: 1957 AAU Mr. America at Peabody Auditorium, Daytona Beach
    {"contest": "Mr America - AAU", "year": "1957",
     "venue": "Peabody Auditorium",
     "location": "Daytona Beach, Florida, USA"},
    # md10018.xml: 1972 NABBA Mr. Universe in London (no venue named)
    {"contest": "Mr Universe - NABBA", "year": "1971",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1971",
     "location": "London, England, UK"},
    {"contest": "Mr Universe - NABBA", "year": "1972",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1972",
     "location": "London, England, UK"},
    # md10098.xml: 1973 AAU Mr. America in Williamsburg, VA (no venue or date)
    {"contest": "Mr America - AAU", "year": "1973",
     "location": "Williamsburg, Virginia, USA"},
    # md110734.xml: 1974 AAU Mr. America in York, PA (York Barbell gym)
    {"contest": "Mr America - AAU", "year": "1974",
     "location": "York, Pennsylvania, USA"},
    # md140520.xml: 1977 AAU Mr. America at Santa Monica Auditorium, July 16
    {"contest": "Mr America - AAU", "year": "1977",
     "date": "July 16, 1977", "venue": "Santa Monica Auditorium",
     "location": "Santa Monica, California, USA"},
    # md150120.xml: 1977 NABBA Mr. Universe in London (no venue named)
    {"contest": "Mr Universe - NABBA", "year": "1977",
     "location": "London, England, UK"},
    {"contest": "Universe - Pro - NABBA", "year": "1977",
     "location": "London, England, UK"},
    # md150630.xml: 1978 AAU Mr. America at Cincinnati Music Hall, September 2
    {"contest": "Mr America - AAU", "year": "1978",
     "date": "September 2, 1978", "venue": "Cincinnati Music Hall",
     "location": "Cincinnati, Ohio, USA"},

    # --- Session 7: files 251-300 --- sh/ Strength & Health 1940s-1950s
    # sh500714.xml: 1950 AAU Mr. America at Academy of Music, Philadelphia, May 12-13
    {"contest": "Mr America - AAU", "year": "1950",
     "date": "May 12-13, 1950", "venue": "Academy of Music",
     "location": "Philadelphia, Pennsylvania, USA"},
    # sh481010.xml + sh481110.xml: Mr Universe - NABBA 1948, Scala Theatre, London, August 13
    {"contest": "Mr Universe - NABBA", "year": "1948",
     "date": "August 13, 1948", "venue": "Scala Theatre",
     "location": "London, England, UK"},
    # sh500926.xml: Mr Universe - NABBA 1950, Scala Theatre, London, June 24
    {"contest": "Mr Universe - NABBA", "year": "1950",
     "date": "June 24, 1950", "venue": "Scala Theatre",
     "location": "London, England, UK"},
    # sh461224.xml: Pro Mr America 1946, San Francisco, September 27 (no venue named)
    {"contest": "Pro Mr America", "year": "1946",
     "date": "September 27, 1946",
     "location": "San Francisco, California, USA"},
    # sh501218.xml: World-Universe - FICH 1950, Paris, October 15
    {"contest": "World-Universe - FICH", "year": "1950",
     "date": "October 15, 1950",
     "location": "Paris, France"},
    # sh501218.xml: Best Developed Athlete in America - IFBB 1950, NYC, September 8
    {"contest": "Best Developed Athlete in America - IFBB", "year": "1950",
     "date": "September 8, 1950",
     "location": "New York, New York, USA"},
    # sh490612.xml: Junior Mr America - AAU 1949, Chattanooga, May 1
    {"contest": "Junior Mr America - AAU", "year": "1949",
     "date": "May 1, 1949",
     "location": "Chattanooga, Tennessee, USA"},
    # sh481110.xml: Mr France 1948, Cannes, August 15; Mr Europe + Mr World 1948, Cannes, August 16
    {"contest": "Mr France", "year": "1948",
     "date": "August 15, 1948",
     "location": "Cannes, France"},
    {"contest": "Mr Europe", "year": "1948",
     "date": "August 16, 1948",
     "location": "Cannes, France"},
    {"contest": "Mr World", "year": "1948",
     "date": "August 16, 1948",
     "location": "Cannes, France"},
    # --- Session 8: files 301-350 --- sh/ Strength & Health 1950s-1960s
    # sh51099.xml: 1951 Mr America at Greek Theatre, Griffith Park, LA — already in DB
    # sh521019.xml: 1952 AAU Mr Universe — placeholder, skip
    # sh53017.xml: 1952 Mr World at "the Met", Philadelphia, October 25 — NEW
    {"contest": "Mr World", "year": "1952",
     "date": "October 25, 1952", "venue": "the Met",
     "location": "Philadelphia, Pennsylvania, USA"},
    # sh530926.xml: 1953 Mr America, Indianapolis — already in DB (Murat Theater)
    # sh541028.xml: 1954 Mr America, Greek Theatre, LA — already in DB (date conflict persists)
    # sh550228.xml: 1954 World-Universe - FICH, Roubaix, France, October 16 — NEW
    {"contest": "World-Universe - FICH", "year": "1954",
     "date": "October 16, 1954",
     "location": "Roubaix, France"},
    # sh550924.xml: 1955 Mr America — already in DB (Masonic Auditorium, Cleveland)
    # sh551030.xml: 1955 NABBA Mr Universe (Amateur), Scala Theatre, London, June 10-11
    #   NOTE: DB has "London Palladium" for 1955 — CONFLICT, do not overwrite
    # sh551030.xml: 1955 NABBA Mr Universe (Pro), Scala Theatre, London, June 10-11 — NEW
    {"contest": "Universe - Pro - NABBA", "year": "1955",
     "date": "June 10-11, 1955", "venue": "Scala Theatre",
     "location": "London, England, UK"},
    # sh560148.xml: 1955 FHIC/FICH Mr Universe (World-Universe - FICH), Munich, October 12-17 — NEW
    {"contest": "World-Universe - FICH", "year": "1955",
     "date": "October 12-17, 1955",
     "location": "Munich, Germany"},
    # sh581018.xml: 1958 Mr America — already in DB (Embassy Auditorium, LA)
    # sh601014.xml: 1960 Mr America, Cleveland — NOT in DB — NEW (location only)
    {"contest": "Mr America - AAU", "year": "1960",
     "location": "Cleveland, Ohio, USA"},
    # sh611016.xml: 1961 Mr America, Santa Monica, June 24 — already in DB (Santa Monica Civic Aud.)
    # sh631017.xml: 1963 Mr America, Zembo Mosque, Harrisburg, PA, June 28-29 — NEW
    {"contest": "Mr America - AAU", "year": "1963",
     "date": "June 28-29, 1963", "venue": "Zembo Mosque",
     "location": "Harrisburg, Pennsylvania, USA"},
    # sh640940.xml: 1964 Mr America — already in DB (Chicago, June 13-14)
    # sh660322.xml: 1965 FIHC Mr Universe, Teheran, Iran — NEW
    {"contest": "World-Universe - FICH", "year": "1965",
     "location": "Tehran, Iran"},
    # sh660322.xml: 1947 FIHC Mr Universe, Philadelphia (first FIHC contest, Steve Stanko won) — NEW
    {"contest": "World-Universe - FICH", "year": "1947",
     "location": "Philadelphia, Pennsylvania, USA"},
    # sh660922.xml: 1966 Mr America, York High School Auditorium — already in DB (York, PA; location filled, skip)
    # --- Session 9: files 351-382 ---
    # sh670920.xml: 1967 Mr America at Veterans' Memorial Auditorium, Columbus — DB has location only; add venue
    {"contest": "Mr America - AAU", "year": "1967",
     "venue": "Veterans' Memorial Auditorium"},
    # sh680918.xml: 1968 Mr America, June 8 — DB has location only; add date+venue (not adding location to avoid conflict)
    {"contest": "Mr America - AAU", "year": "1968",
     "date": "June 8, 1968", "venue": "William Penn High School Auditorium"},
    # yp160316.xml: 1951 Mr Universe - NABBA, Scala Theatre, London, September 1 — NEW
    {"contest": "Mr Universe - NABBA", "year": "1951",
     "date": "September 1, 1951", "venue": "Scala Theatre",
     "location": "London, England, UK"},
    # --- Scorecard scraping page 37 (2021 contests) ---
    {"contest": "Battle of Champions Pro - IFBB", "year": "2021",
     "date": "August 29, 2021", "location": "Warsaw, Poland"},
    {"contest": "Tokyo Supershow Pro - IFBB", "year": "2021",
     "date": "August 29, 2021", "location": "Tokyo, Japan"},
    {"contest": "Nashville FitShow Pro - IFBB", "year": "2021",
     "date": "August 21, 2021", "location": "Nashville, Tennessee, USA"},
    {"contest": "Europa Pro - IFBB", "year": "2021",
     "date": "August 15, 2021", "location": "Alicante, Spain"},
    {"contest": "Tahoe Pro - IFBB", "year": "2021",
     "date": "August 15, 2021", "location": "Stateline, Nevada, USA"},
    {"contest": "Pacific USA Pro - IFBB", "year": "2021",
     "date": "August 5, 2021", "location": "San Diego, California, USA"},
    {"contest": "Puerto Vallarta Pro - IFBB", "year": "2021",
     "date": "July 31-August 1, 2021", "location": "Puerto Vallarta, Jalisco, Mexico"},
    {"contest": "Battle of the Bodies Pro - IFBB", "year": "2021",
     "date": "July 31, 2021", "location": "Fort Lauderdale, Florida, USA"},
    # --- Scorecard scraping page 36 (2021 contests) ---
    {"contest": "Minneapolis Pro - IFBB", "year": "2021",
     "date": "October 2, 2021", "location": "Minneapolis, Minnesota, USA"},
    {"contest": "Nashville Night of Champions Pro - IFBB", "year": "2021",
     "date": "October 2, 2021", "location": "Chattanooga, Tennessee, USA"},
    {"contest": "Arnold Classic - IFBB", "year": "2021",
     "date": "September 25, 2021", "location": "Columbus, Ohio, USA"},
    {"contest": "San Antonio Pro - IFBB", "year": "2021",
     "date": "September 25, 2021", "location": "San Antonio, Texas, USA"},
    {"contest": "Champions Classic Pro - IFBB", "year": "2021",
     "date": "September 19, 2021", "location": "Warsaw, Poland"},
    {"contest": "Heart of Texas Pro - IFBB", "year": "2021",
     "date": "September 18, 2021", "location": "Dallas, Texas, USA"},
    {"contest": "Monsterzym Pro - IFBB", "year": "2021",
     "date": "September 12, 2021", "location": "Seoul, South Korea"},
    {"contest": "Rising Phoenix Pro - IFBB", "year": "2021",
     "date": "September 11, 2021", "location": "Scottsdale, Arizona, USA"},
    {"contest": "Powerhouse Classic Pro - IFBB", "year": "2021",
     "date": "September 11, 2021", "location": "Ypsilanti, Michigan, USA"},
    {"contest": "Lenda Murray Savannah Pro - IFBB", "year": "2021",
     "date": "September 4, 2021", "location": "Savannah, Georgia, USA"},
    # --- Scorecard scraping page 35 (2021 contests) ---
    {"contest": "Hurricane Pro - IFBB", "year": "2021",
     "date": "October 23, 2021", "location": "St. Petersburg, Florida, USA"},
    {"contest": "San Antonio Classic Pro - IFBB", "year": "2021",
     "date": "October 23, 2021", "location": "San Antonio, Texas, USA"},
    {"contest": "FitParade Pro - IFBB", "year": "2021",
     "date": "October 16-17, 2021", "location": "Budapest, Hungary"},
    {"contest": "Yamamoto Cup Pro - IFBB", "year": "2021",
     "date": "October 17, 2021", "location": "Rome, Italy"},
    {"contest": "Monterrey Pro - IFBB", "year": "2021",
     "date": "October 16, 2021", "location": "Monterrey, Mexico"},
    {"contest": "Kentucky Muscle Pro - IFBB", "year": "2021",
     "date": "October 16, 2021", "location": "Louisville, Kentucky, USA"},
    {"contest": "Titans Grand Prix Pro - IFBB", "year": "2021",
     "date": "October 16, 2021", "location": "Los Angeles, California, USA"},
    {"contest": "Amateur Olympia Orlando - NPC Worldwide", "year": "2021",
     "date": "October 5, 2021", "location": "Orlando, Florida, USA"},
    {"contest": "Arnold Classic United Kingdom - IFBB", "year": "2021",
     "date": "October 1-2, 2021", "location": "Birmingham, United Kingdom"},
    # --- Scorecard scraping page 34 re-run (2021 contests) ---
    {"contest": "MuscleContest Brazil Pro - IFBB", "year": "2021",
     "date": "November 26-28, 2021", "location": "Brazil"},
    {"contest": "Shawn Ray Hawaiian Classic Pro - IFBB", "year": "2021",
     "date": "November 20, 2021", "location": "Honolulu, Hawaii, USA"},
    {"contest": "Atlantic Coast Pro - IFBB", "year": "2021",
     "date": "November 20, 2021", "location": "Fort Lauderdale, Florida, USA"},
    {"contest": "Ben Weider Natural Pro - IFBB", "year": "2021",
     "date": "November 19, 2021", "location": "Alexandria, Virginia, USA"},
    {"contest": "Romania Muscle Fest Pro - IFBB", "year": "2021",
     "date": "November 13-14, 2021", "location": "Bucharest, Romania"},
    {"contest": "Texas State Pro - IFBB", "year": "2021",
     "date": "November 13, 2021", "location": "Austin, Texas, USA"},
    {"contest": "Iron Games Pro - IFBB", "year": "2021",
     "date": "November 13, 2021", "location": "Anaheim, California, USA"},
    {"contest": "Sacramento Pro - IFBB", "year": "2021",
     "date": "November 6, 2021", "location": "Sacramento, California, USA"},
    {"contest": "EVLS Prague Pro - IFBB", "year": "2021",
     "date": "November 6, 2021", "location": "Prague, Czech Republic"},
    {"contest": "KO Egypt Pro - IFBB", "year": "2021",
     "date": "October 31, 2021", "location": "Cairo, Egypt"},
    {"contest": "MuscleContest Nacional Pro - IFBB", "year": "2021",
     "date": "October 30, 2021", "location": "Campinas, Brazil"},
    {"contest": "Legion Sports Fest Pro - IFBB", "year": "2021",
     "date": "October 24, 2021", "location": "Reno, Nevada, USA"},
    {"contest": "Poland Pro Supershow - IFBB", "year": "2021",
     "date": "October 24, 2021", "location": "Warsaw, Poland"},
    # --- Scorecard scraping page 33 re-run (2022/2021 contests) ---
    {"contest": "MuscleContest Campinas Pro - IFBB", "year": "2022",
     "date": "March 19, 2022", "location": "Campinas, Brazil"},
    {"contest": "Boston Pro - IFBB", "year": "2022",
     "date": "March 12, 2022", "location": "Boston, Massachusetts, USA"},
    {"contest": "Arnold Classic - IFBB", "year": "2022",
     "date": "March 5, 2022", "location": "Columbus, Ohio, USA"},
    {"contest": "National Championships - NPC", "year": "2021",
     "date": "December 17, 2021"},
    {"contest": "Atlanta All States Pro - IFBB", "year": "2021",
     "date": "December 10-11, 2021", "location": "Atlanta, Georgia, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2021",
     "date": "December 5, 2021", "location": "Toronto, Canada"},
    {"contest": "Battle of Texas Pro - IFBB", "year": "2021",
     "date": "December 4, 2021", "location": "Irving, Texas, USA"},
    {"contest": "Pro Bigman Weekend - IFBB", "year": "2021",
     "date": "November 28, 2021", "location": "Alicante, Spain"},
    {"contest": "Vancouver Pro - IFBB", "year": "2021",
     "date": "December 22, 2021", "location": "Vancouver, Canada"},
    {"contest": "New Zealand Pro - IFBB", "year": "2021",
     "date": "December 18, 2021", "location": "Auckland, New Zealand"},
    # --- Scorecard scraping page 32 re-run (2022 contests) ---
    {"contest": "GRL PWR Pro - IFBB", "year": "2022",
     "date": "April 30, 2022", "location": "Orlando, Florida, USA"},
    {"contest": "Warrior Classic Pro - IFBB", "year": "2022",
     "date": "April 30, 2022", "location": "Richmond, Virginia, USA"},
    {"contest": "Fitmuscle Pro - IFBB", "year": "2022",
     "date": "April 23, 2022", "location": "Guadalajara, Mexico"},
    {"contest": "Wasatch Warrior Pro - IFBB", "year": "2022",
     "date": "April 15, 2022", "location": "Salt Lake City, Utah, USA"},
    {"contest": "Charlotte Cup Pro - IFBB", "year": "2022",
     "date": "April 15-16, 2022", "location": "Charlotte, North Carolina, USA"},
    {"contest": "St. Louis Pro - IFBB", "year": "2022",
     "date": "April 16, 2022", "location": "St. Louis, Missouri, USA"},
    {"contest": "Golden State Pro - IFBB", "year": "2022",
     "date": "April 9, 2022", "location": "Sacramento, California, USA"},
    {"contest": "World Klash Pro - IFBB", "year": "2022",
     "date": "April 2, 2022", "location": "Orlando, Florida, USA"},
    {"contest": "MuscleContest Rio Pro - IFBB", "year": "2022",
     "date": "March 26, 2022", "location": "Rio de Janeiro, Brazil"},
    {"contest": "Caribbean Grand Prix Bermuda Pro - IFBB", "year": "2022",
     "date": "March 26, 2022", "location": "Hamilton, Bermuda"},
    {"contest": "Fitworld Pro - IFBB", "year": "2022",
     "date": "March 19, 2022", "location": "Anaheim, California, USA"},
    # --- Scorecard scraping page 31 re-run (2022 contests) ---
    {"contest": "Mile High Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "Denver, Colorado, USA"},
    {"contest": "Clash at the Titanz Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "Marietta, Georgia, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2022",
     "date": "June 5, 2022", "location": "Toronto, Canada"},
    {"contest": "Miami Muscle Beach Pro - IFBB", "year": "2022",
     "date": "June 4, 2022", "location": "Miami Beach, Florida, USA"},
    {"contest": "Mid-USA Pro - IFBB", "year": "2022",
     "date": "May 28, 2022", "location": "Albuquerque, New Mexico, USA"},
    {"contest": "California State Pro - IFBB", "year": "2022",
     "date": "May 28, 2022", "location": "San Diego, California, USA"},
    {"contest": "Palmetto Classic Pro - IFBB", "year": "2022",
     "date": "May 28, 2022", "location": "Columbia, South Carolina, USA"},
    {"contest": "Optimum Classic Pro - IFBB", "year": "2022",
     "date": "May 21, 2022", "location": "Shreveport, Louisiana, USA"},
    {"contest": "Indy Pro - IFBB", "year": "2022",
     "date": "May 14, 2022", "location": "Indianapolis, Indiana, USA"},
    {"contest": "Pittsburgh Championships - NPC", "year": "2022",
     "date": "May 6, 2022", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Florida Grand Prix Pro - IFBB", "year": "2022",
     "date": "May 7, 2022", "location": "Boca Raton, Florida, USA"},
    # --- Scorecard scraping page 30 re-run (2022 contests) ---
    {"contest": "Sheru Classic Italian Pro - IFBB", "year": "2022",
     "date": "June 26, 2022", "location": "Rome, Italy"},
    {"contest": "MuscleContest Brazil Pro - IFBB", "year": "2022",
     "date": "June 24, 2022", "location": "Rio de Janeiro, Brazil"},
    {"contest": "Puerto Rico Pro - IFBB", "year": "2022",
     "date": "June 17-19, 2022", "location": "San Juan, Puerto Rico"},
    {"contest": "Dallas Pro - IFBB", "year": "2022",
     "date": "June 18, 2022", "location": "Dallas, Texas, USA"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2022",
     "date": "June 18, 2022", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "Omaha, Nebraska, USA"},
    {"contest": "Southern California Championships Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "San Diego, California, USA"},
    {"contest": "DC Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "Alexandria, Virginia, USA"},
    {"contest": "Northern California Pro - IFBB", "year": "2022",
     "date": "June 11, 2022", "location": "Sacramento, California, USA"},
    # --- Scorecard scraping page 66 (2017 contests) ---
    {"contest": "Governors Cup Pro - IFBB", "year": "2017",
     "date": "April 1, 2017", "location": "Sacramento, California, USA"},
    {"contest": "City Limits Pro - IFBB", "year": "2017",
     "date": "April 1, 2017", "location": "Waxahachie, Texas, USA"},
    {"contest": "Karina Nascimento Pro - IFBB", "year": "2017",
     "date": "March 25, 2017", "location": "Fort Lauderdale, Florida, USA"},
    {"contest": "Fitworld Pro - IFBB", "year": "2017",
     "date": "March 11, 2017", "location": "Culver City, California, USA"},
    {"contest": "Orlando Pro - IFBB", "year": "2017",
     "date": "March 11, 2017", "location": "Orlando, Florida, USA"},
    {"contest": "Arnold Classic - IFBB", "year": "2017",
     "date": "March 3, 2017", "location": "Columbus, Ohio, USA"},
    {"contest": "Legends Classic Pro - IFBB", "year": "2017",
     "date": "February 11, 2017", "location": "Las Vegas, Nevada, USA"},
    # --- Scorecard scraping page 65 (2017 contests) ---
    {"contest": "Optimum Classic Pro - IFBB", "year": "2017",
     "date": "May 20, 2017", "location": "Shreveport, Louisiana, USA"},
    {"contest": "Florida Grand Prix Masters Pro - IFBB", "year": "2017",
     "date": "May 7, 2017", "location": "West Palm Beach, Florida, USA"},
    {"contest": "California Night of Champions Pro - IFBB", "year": "2017",
     "date": "May 6, 2017", "location": "San Diego, California, USA"},
    {"contest": "Pittsburgh Pro - IFBB", "year": "2017",
     "date": "May 6, 2017", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Europa Charlotte Pro - IFBB", "year": "2017",
     "date": "April 23, 2017", "location": "Charlotte, North Carolina, USA"},
    {"contest": "St. Louis Pro - IFBB", "year": "2017",
     "date": "April 15, 2017", "location": "St. Louis, Missouri, USA"},
    {"contest": "Los Angeles Grand Prix Pro - IFBB", "year": "2017",
     "date": "April 8, 2017", "location": "Culver City, California, USA"},
    # --- Scorecard scraping page 64 (2017 contests) ---
    {"contest": "Miami Muscle Beach Pro - IFBB", "year": "2017",
     "date": "June 10, 2017", "location": "Miami Beach, Florida, USA"},
    {"contest": "Puerto Rico Pro - IFBB", "year": "2017",
     "date": "June 4, 2017"},
    {"contest": "Northern California Pro - IFBB", "year": "2017",
     "date": "June 3, 2017", "location": "Sacramento, California, USA"},
    {"contest": "California State Pro - IFBB", "year": "2017",
     "date": "May 27, 2017", "location": "Culver City, California, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2017",
     "date": "May 28, 2017", "location": "Toronto, Canada"},
    {"contest": "Ostrava Pro - IFBB", "year": "2017",
     "date": "May 27, 2017", "location": "Ostrava, Czech Republic"},
    {"contest": "Europa Pro - IFBB", "year": "2017",
     "date": "May 21, 2017", "location": "Orlando, Florida, USA"},
    {"contest": "New York Pro Championships - IFBB", "year": "2017",
     "date": "May 20, 2017", "location": "New York, New York, USA"},
    # --- Scorecard scraping page 63 (2017 contests) ---
    {"contest": "Baltimore Pro - IFBB", "year": "2017",
     "date": "July 15, 2017", "location": "Baltimore, Maryland, USA"},
    {"contest": "Lenda Murray Pro - IFBB", "year": "2017",
     "date": "July 8, 2017", "location": "Norfolk, Virginia, USA"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2017",
     "date": "July 1, 2017", "location": "Las Vegas, Nevada, USA"},
    {"contest": "San Jose Pro - IFBB", "year": "2017",
     "date": "July 1, 2017", "location": "San Jose, California, USA"},
    {"contest": "Chicago Pro - IFBB", "year": "2017",
     "date": "June 30, 2017"},
    {"contest": "Arctic Pro - IFBB", "year": "2017",
     "date": "June 24, 2017", "location": "Anchorage, Alaska, USA"},
    {"contest": "Greater Gulf Pro - IFBB", "year": "2017",
     "date": "June 24, 2017", "location": "New Orleans, Louisiana, USA"},
    {"contest": "Dexter Jackson Memphis Classic Pro - IFBB", "year": "2017",
     "date": "June 24, 2017", "location": "Memphis, Tennessee, USA"},
    # --- Scorecard scraping page 62 (2017 contests) ---
    {"contest": "Rising Phoenix Pro - IFBB", "year": "2017",
     "date": "September 9, 2017", "location": "Phoenix, Arizona, USA"},
    {"contest": "Pittsburgh Pro Masters Championships - IFBB", "year": "2017",
     "date": "August 30, 2017", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Pacific USA Pro - IFBB", "year": "2017",
     "date": "August 19, 2017", "location": "San Diego, California, USA"},
    {"contest": "Golden State Pro - IFBB", "year": "2017",
     "date": "August 12, 2017", "location": "Sacramento, California, USA"},
    {"contest": "San Antonio Pro - IFBB", "year": "2017",
     "date": "August 12, 2017", "location": "San Antonio, Texas, USA"},
    {"contest": "Tampa Pro - IFBB", "year": "2017",
     "date": "August 5, 2017", "location": "Tampa, Florida, USA"},
    # --- Scorecard scraping page 61 (2017 contests) ---
    {"contest": "Titans Grand Prix Pro - IFBB", "year": "2017",
     "date": "October 21, 2017", "location": "Culver City, California, USA"},
    {"contest": "South Carolina Grand Prix Pro - IFBB", "year": "2017",
     "date": "October 21, 2017", "location": "Charleston, South Carolina, USA"},
    {"contest": "Central USA Pro - IFBB", "year": "2017",
     "date": "October 14, 2017", "location": "Sioux Falls, South Dakota, USA"},
    {"contest": "San Antonio Classic Pro - IFBB", "year": "2017",
     "date": "October 7, 2017", "location": "San Antonio, Texas, USA"},
    {"contest": "EVLS Prague Pro - IFBB", "year": "2017",
     "date": "September 30, 2017", "location": "Prague, Czech Republic"},
    {"contest": "Arkansas Pro - IFBB", "year": "2017",
     "date": "September 23, 2017", "location": "Little Rock, Arkansas, USA"},
    {"contest": "Arnold Classic Europe - IFBB", "year": "2017",
     "date": "September 23, 2017", "location": "Barcelona, Spain"},
    {"contest": "Olympia - IFBB", "year": "2017",
     "date": "September 16, 2017", "location": "Las Vegas, Nevada, USA"},
    # --- Scorecard scraping page 60 (2017-2018 contests) ---
    {"contest": "Legends Pro - IFBB", "year": "2018",
     "date": "February 10, 2018", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Tournament of Champions Pro - IFBB", "year": "2017",
     "date": "December 2, 2017", "location": "San Diego, California, USA"},
    {"contest": "Ferrigno Legacy Pro - IFBB", "year": "2017",
     "date": "November 18, 2017", "location": "Rancho Mirage, California, USA"},
    {"contest": "Iron Games Pro - IFBB", "year": "2017",
     "date": "November 11, 2017", "location": "Culver City, California, USA"},
    {"contest": "Ultimate Warriors Pro - IFBB", "year": "2017",
     "date": "November 4, 2017", "location": "San Diego, California, USA"},
    {"contest": "Sacramento Pro - IFBB", "year": "2017",
     "date": "October 28, 2017", "location": "Sacramento, California, USA"},
    {"contest": "Kentucky Muscle Pro - IFBB", "year": "2017",
     "date": "October 28, 2017", "location": "Louisville, Kentucky, USA"},
    {"contest": "Mel Chancey Pro - IFBB", "year": "2017",
     "date": "October 28, 2017", "location": "Fort Myers, Florida, USA"},
    # --- Scorecard scraping page 59 (2018 contests) ---
    {"contest": "Atlantic Coast Pro - IFBB", "year": "2018",
     "date": "March 24, 2018", "location": "Fort Lauderdale, Florida, USA"},
    {"contest": "Royal London Pro - IFBB", "year": "2018",
     "date": "March 10-11, 2018", "location": "London, England, UK"},
    {"contest": "Hawaii Pro - IFBB", "year": "2018",
     "date": "March 10, 2018", "location": "Honolulu, Hawaii, USA"},
    {"contest": "Arnold Classic - IFBB", "year": "2018",
     "date": "March 3, 2018", "location": "Columbus, Ohio, USA"},
    {"contest": "Sheru Classic Colombia Pro - IFBB", "year": "2018",
     "date": "February 18, 2018", "location": "Medellin, Colombia"},
    # --- Scorecard scraping page 67 (2016 contests) ---
    {"contest": "San Marino Pro - IFBB", "year": "2016",
     "date": "December 4, 2016", "location": "San Marino"},
    {"contest": "Tournament of Champions Pro - IFBB", "year": "2016",
     "date": "December 3, 2016", "location": "San Diego, California, USA"},
    {"contest": "Iron Games Pro - IFBB", "year": "2016",
     "date": "November 12, 2016", "location": "Culver City, California, USA"},
    {"contest": "Florida Victory Pro - IFBB", "year": "2016",
     "date": "November 5, 2016", "location": "Boca Raton, Florida, USA"},
    {"contest": "Ultimate Warriors Pro - IFBB", "year": "2016",
     "date": "November 5, 2016", "location": "San Diego, California, USA"},
    {"contest": "Sacramento Pro - IFBB", "year": "2016",
     "date": "November 5, 2016", "location": "Sacramento, California, USA"},
    {"contest": "Moscow Pro - IFBB", "year": "2016",
     "date": "October 30, 2016", "location": "Moscow, Russia"},
    {"contest": "Ferrigno Legacy Pro - IFBB", "year": "2016",
     "date": "October 29, 2016", "location": "Rancho Mirage, California, USA"},
    {"contest": "Nationals - NPC", "year": "2016",
     "date": "November 18-19, 2016"},
    # --- Scorecard scraping page 68 (2016 contests) ---
    {"contest": "Titans Grand Prix Pro - IFBB", "year": "2016",
     "date": "October 15, 2016", "location": "Culver City, California, USA"},
    {"contest": "Border States Pro - IFBB", "year": "2016",
     "date": "October 1, 2016", "location": "San Diego, California, USA"},
    # Skipped: Europa Phoenix Pro (not in DB), Liquid Sun Rayz Pro (not in DB),
    #          Nordic Pro (not in DB), Fort Lauderdale Cup Pro (not in DB)
    # --- Scorecard scraping page 69 (2016 contests) ---
    {"contest": "Kuwait Pro Championships - IFBB", "year": "2016",
     "date": "September 29, 2016", "location": "Kuwait"},
    {"contest": "Asia Grand Prix - IFBB", "year": "2016",
     "date": "September 25, 2016", "location": "Seoul, South Korea"},
    {"contest": "Hurricane Pro - IFBB", "year": "2016",
     "date": "September 24, 2016", "location": "Tampa, Florida, USA"},
    {"contest": "Arnold Classic Europe - IFBB", "year": "2016",
     "date": "September 24, 2016", "location": "Barcelona, Spain"},
    {"contest": "Arkansas Pro - IFBB", "year": "2016",
     "date": "September 24, 2016", "location": "Little Rock, Arkansas, USA"},
    {"contest": "Olympia - IFBB", "year": "2016",
     "date": "September 17, 2016", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Pacific USA Pro - IFBB", "year": "2016",
     "date": "September 3, 2016", "location": "San Diego, California, USA"},
    {"contest": "Pittsburgh Pro Masters Championships - IFBB", "year": "2016",
     "date": "August 31, 2016", "location": "Pittsburgh, Pennsylvania, USA"},
    # Skipped: Kuwait Pro (not in DB), Arizona Pro/Rising Phoenix 2016 (not in DB),
    #          North American Championships (no date/location in scorecard)
    # --- Scorecard scraping page 70 (2016 contests) ---
    {"contest": "Arnold Classic Asia - IFBB", "year": "2016",
     "date": "August 20, 2016", "location": "Hong Kong"},
    {"contest": "Golden State Pro - IFBB", "year": "2016",
     "date": "August 13, 2016", "location": "Sacramento, California, USA"},
    {"contest": "San Antonio Pro - IFBB", "year": "2016",
     "date": "August 13, 2016", "location": "San Antonio, Texas, USA"},
    {"contest": "Tampa Pro - IFBB", "year": "2016",
     "date": "August 6, 2016", "location": "Tampa, Florida, USA"},
    {"contest": "Prestige Crystal Cup Pro - IFBB", "year": "2016",
     "date": "July 30, 2016", "location": "Boca Raton, Florida, USA"},
    # Skipped: Naples Pro (not in DB), Coastal USA Pro (not in DB),
    #          Flex Lewis Classic Pro (not in DB)
    # --- Scorecard scraping page 71 (2016 contests) ---
    {"contest": "Europa Charlotte Pro - IFBB", "year": "2016",
     "date": "July 9, 2016", "location": "Charlotte, North Carolina, USA"},
    {"contest": "San Jose Pro - IFBB", "year": "2016",
     "date": "July 2, 2016", "location": "San Jose, California, USA"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2016",
     "date": "July 2, 2016", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Chicago Pro - IFBB", "year": "2016",
     "date": "July 2, 2016", "location": "Chicago, Illinois, USA"},
    {"contest": "Greater Gulf Pro - IFBB", "year": "2016",
     "date": "June 25, 2016", "location": "New Orleans, Louisiana, USA"},
    {"contest": "Dexter Jackson Memphis Classic Pro - IFBB", "year": "2016",
     "date": "June 25, 2016", "location": "Memphis, Tennessee, USA"},
    {"contest": "Europa Dallas - IFBB", "year": "2016",
     "date": "June 18, 2016", "location": "Dallas, Texas, USA"},
    # --- Scorecard scraping page 72 (2016 contests) ---
    {"contest": "Arctic Pro - IFBB", "year": "2016",
     "date": "June 11, 2016", "location": "Anchorage, Alaska, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2016",
     "date": "June 5, 2016", "location": "Toronto, Canada"},
    {"contest": "Northern California Pro - IFBB", "year": "2016",
     "date": "June 4, 2016", "location": "Sacramento, California, USA"},
    {"contest": "Mile High Pro - IFBB", "year": "2016",
     "date": "June 4, 2016", "location": "Denver, Colorado, USA"},
    {"contest": "California Pro - IFBB", "year": "2016",
     "date": "May 28, 2016", "location": "Culver City, California, USA"},
    {"contest": "Arnold Classic South Africa - IFBB", "year": "2016",
     "date": "May 28, 2016", "location": "Johannesburg, South Africa"},
    # Skipped: Muscle Mayhem Pro (404 error)
    # --- Scorecard scraping page 73 (2016 contests) ---
    {"contest": "New York Pro Championships - IFBB", "year": "2016",
     "date": "May 21, 2016", "location": "Teaneck, New Jersey, USA"},
    {"contest": "Florida Grand Prix Pro - IFBB", "year": "2016",
     "date": "May 14, 2016", "location": "West Palm Beach, Florida, USA"},
    {"contest": "California Night of Champions Pro - IFBB", "year": "2016",
     "date": "May 7, 2016", "location": "San Diego, California, USA"},
    {"contest": "Pittsburgh Pro - IFBB", "year": "2016",
     "date": "May 7, 2016", "location": "Pittsburgh, Pennsylvania, USA"},
    # Skipped: Body Power Pro (not in DB)
    # --- Scorecard scraping page 74 (2016 contests) ---
    {"contest": "Governors Cup Pro - IFBB", "year": "2016",
     "date": "March 26, 2016", "location": "Sacramento, California, USA"},
    {"contest": "St. Louis Pro - IFBB", "year": "2016",
     "date": "March 26, 2016", "location": "St. Louis, Missouri, USA"},
    {"contest": "Orlando Pro - IFBB", "year": "2016",
     "date": "March 12, 2016", "location": "Orlando, Florida, USA"},
    # Skipped: LA Grand Prix Pro 2016 (not in DB), MuscleContest Pro 2016 (not in DB),
    #          Phil Heath Classic Pro (not in DB)
]

_page25 = [
    # Page 25
    {"contest": "Battle of Texas Pro - IFBB", "year": "2022",
     "date": "December 10, 2022", "location": "Irving, Texas, USA"},
    {"contest": "Big Man Pro - IFBB", "year": "2022",
     "date": "November 27, 2022", "location": "Alicante, Spain"},
    {"contest": "Taiwan Pro - IFBB", "year": "2022",
     "date": "November 27, 2022", "location": "Taiwan"},
    {"contest": "Shawn Ray Hawaiian Classic Pro - IFBB", "year": "2022",
     "date": "November 19, 2022", "location": "Honolulu, Hawaii, USA"},
    {"contest": "Romania Muscle Fest Pro - IFBB", "year": "2022",
     "date": "November 12-13, 2022", "location": "Bucharest, Romania"},
    {"contest": "Sacramento Pro - IFBB", "year": "2022",
     "date": "November 12, 2022", "location": "Sacramento, California, USA"},
    {"contest": "MuscleContest Mercosul Pro - IFBB", "year": "2022",
     "date": "December 12, 2022", "location": "Novo Hamburgo, Brazil"},
    {"contest": "Europa Pro Championships - IFBB", "year": "2022",
     "date": "November 4-6, 2022", "location": "Spain"},
    {"contest": "MuscleContest FitPira Pro - IFBB", "year": "2022",
     "date": "November 6, 2022", "location": "Piracicaba, Brazil"},
]

_page24 = [
    # Page 24
    {"contest": "Houston Tournament of Champions Pro - IFBB", "year": "2023",
     "date": "April 1, 2023", "location": "Houston, Texas, USA"},
    {"contest": "Tri-City Pro - IFBB", "year": "2023",
     "date": "March 31 - April 1, 2023", "location": "Columbus, Georgia, USA"},
    {"contest": "MuscleContest Rio de Janeiro Pro - IFBB", "year": "2023",
     "date": "March 25, 2023", "location": "Rio de Janeiro, Brazil"},
    {"contest": "Sampson Showdown Pro - IFBB", "year": "2023",
     "date": "March 25, 2023", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Klash Series Championships Pro - IFBB", "year": "2023",
     "date": "March 25, 2023", "location": "Orlando, Florida, USA"},
    {"contest": "MuscleContest Campinas Pro - IFBB", "year": "2023",
     "date": "March 18, 2023", "location": "Campinas, Brazil"},
    {"contest": "Orchid Pro - IFBB", "year": "2023",
     "date": "February 25, 2023", "location": "Singapore"},
    {"contest": "Japan Pro - IFBB", "year": "2023",
     "date": "February 18-19, 2023", "location": "Japan"},
    {"contest": "Saudi Arabia Pro - IFBB", "year": "2023",
     "date": "January 14, 2023", "location": "Saudi Arabia"},
]

_page23 = [
    # Page 23
    {"contest": "Florida Grand Prix Masters Pro - IFBB", "year": "2023",
     "date": "May 6, 2023", "location": "Boca Raton, Florida, USA"},
    {"contest": "St. Louis Pro - IFBB", "year": "2023",
     "date": "May 6, 2023", "location": "St. Louis, Missouri, USA"},
    {"contest": "GRL PWR Pro - IFBB", "year": "2023",
     "date": "April 29, 2023", "location": "Orlando, Florida, USA"},
    {"contest": "Emerald Cup Pro - IFBB", "year": "2023",
     "date": "April 28, 2023", "location": "Bellevue, Washington, USA"},
    {"contest": "Vancouver Island Showdown Pro - IFBB", "year": "2023",
     "date": "April 23, 2023", "location": "Victoria, British Columbia, Canada"},
    {"contest": "Charlotte Cup Pro - IFBB", "year": "2023",
     "date": "April 22-23, 2023", "location": "Charlotte, North Carolina, USA"},
    {"contest": "Los Angeles Grand Prix Pro - IFBB", "year": "2023",
     "date": "April 22, 2023", "location": "Anaheim, California, USA"},
    {"contest": "Wasatch Warrior Pro - IFBB", "year": "2023",
     "date": "April 15, 2023", "location": "Salt Lake City, Utah, USA"},
    {"contest": "Memphis Pro - IFBB", "year": "2023",
     "date": "April 8, 2023", "location": "Memphis, Tennessee, USA"},
    {"contest": "1 Bro Pro Show - IFBB", "year": "2023",
     "date": "April 8, 2023", "location": "Maidenhead, United Kingdom"},
    {"contest": "Fitworld Pro - IFBB", "year": "2023",
     "date": "April 1, 2023", "location": "Anaheim, California, USA"},
]

_page22 = [
    # Page 22
    {"contest": "Mile High Pro - IFBB", "year": "2023",
     "date": "June 10, 2023", "location": "Denver, Colorado, USA"},
    {"contest": "DC Pro - IFBB", "year": "2023",
     "date": "June 10, 2023", "location": "Alexandria, Virginia, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2023",
     "date": "June 4, 2023", "location": "Toronto, Ontario, Canada"},
    {"contest": "Nevada State Pro - IFBB", "year": "2023",
     "date": "June 3, 2023", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Adela Garcia Pro - IFBB", "year": "2023",
     "date": "June 3, 2023", "location": "Austin, Texas, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2023",
     "date": "June 3, 2023", "location": "Omaha, Nebraska, USA"},
    {"contest": "Miami Muscle Beach Pro - IFBB", "year": "2023",
     "date": "June 3, 2023", "location": "Miami Beach, Florida, USA"},
    {"contest": "Klash Series Southern USA Pro - IFBB", "year": "2023",
     "date": "May 27, 2023", "location": "Orlando, Florida, USA"},
    {"contest": "California State Pro - IFBB", "year": "2023",
     "date": "May 27, 2023", "location": "San Diego, California, USA"},
    {"contest": "Palmetto Classic Pro - IFBB", "year": "2023",
     "date": "May 27, 2023", "location": "Columbia, South Carolina, USA"},
    {"contest": "Junior USA Championships - NPC", "year": "2023",
     "date": "May 19, 2023"},
    {"contest": "Optimum Classic Pro - IFBB", "year": "2023",
     "date": "May 20, 2023", "location": "Shreveport, Louisiana, USA"},
    {"contest": "California Night of Champions Pro - IFBB", "year": "2023",
     "date": "May 13, 2023", "location": "San Diego, California, USA"},
]

_page21 = [
    # Page 21
    {"contest": "Republic of Texas Pro - IFBB", "year": "2023",
     "date": "July 8, 2023", "location": "Austin, Texas, USA"},
    {"contest": "Taiwan Pro - IFBB", "year": "2023",
     "date": "June 30 - July 2, 2023", "location": "Kaohsiung, Taiwan"},
    {"contest": "Orlando Pro - IFBB", "year": "2023",
     "date": "July 1, 2023", "location": "Orlando, Florida, USA"},
    {"contest": "Sheru Classic Italy Pro - IFBB", "year": "2023",
     "date": "June 25, 2023", "location": "Milan, Italy"},
    {"contest": "Empro Pro - IFBB", "year": "2023",
     "date": "June 18, 2023", "location": "Alicante, Spain"},
    {"contest": "Dallas Pro - IFBB", "year": "2023",
     "date": "June 17, 2023", "location": "Dallas, Texas, USA"},
    {"contest": "AGP Pro - IFBB", "year": "2023",
     "date": "June 17, 2023", "location": "South Korea"},
    {"contest": "Northern California Pro - IFBB", "year": "2023",
     "date": "June 10, 2023", "location": "Sacramento, California, USA"},
]

_page20 = [
    # Page 20
    {"contest": "Big Man Pro - IFBB", "year": "2023",
     "date": "July 29, 2023", "location": "Benidorm, Spain"},
    {"contest": "USA Championships - NPC", "year": "2023",
     "date": "July 28, 2023"},
    {"contest": "Vancouver Pro - IFBB", "year": "2023",
     "date": "July 14-16, 2023", "location": "Vancouver, British Columbia, Canada"},
    {"contest": "AGP Bikini Pro - IFBB", "year": "2023",
     "date": "July 15, 2023", "location": "South Korea"},
    {"contest": "Lenda Murray Atlanta Pro - IFBB", "year": "2023",
     "date": "July 15-16, 2023", "location": "Atlanta, Georgia, USA"},
    {"contest": "Mr. Big Evolution Portugal Pro - IFBB", "year": "2023",
     "date": "July 9, 2023", "location": "Portugal"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2023",
     "date": "July 8, 2023", "location": "Las Vegas, Nevada, USA"},
]

_page19 = [
    # Page 19
    {"contest": "RGV Classic Pro - IFBB", "year": "2023",
     "date": "September 2, 2023", "location": "McAllen, Texas, USA"},
    {"contest": "MuscleContest Iron Games Pro - IFBB", "year": "2023",
     "date": "September 2, 2023", "location": "Anaheim, California, USA"},
    {"contest": "Nashville FitShow Pro - IFBB", "year": "2023",
     "date": "August 19, 2023", "location": "Nashville, Tennessee, USA"},
    {"contest": "Pacific USA Pro - IFBB", "year": "2023",
     "date": "August 12, 2023", "location": "San Diego, California, USA"},
]

_page18 = [
    # Page 18
    {"contest": "Daytona Pro - IFBB", "year": "2023",
     "date": "September 29, 2023", "location": "Daytona Beach, Florida, USA"},
    {"contest": "Heart of Texas Pro - IFBB", "year": "2023",
     "date": "September 9, 2023", "location": "Dallas, Texas, USA"},
    {"contest": "Battle of the Bodies Pro - IFBB", "year": "2023",
     "date": "September 16, 2023", "location": "Fort Lauderdale, Florida, USA"},
    {"contest": "Legion Masters Pro - IFBB", "year": "2023",
     "date": "October 7, 2023", "location": "Reno, Nevada, USA"},
    {"contest": "Legion Pro - IFBB", "year": "2023",
     "date": "October 8, 2023", "location": "Reno, Nevada, USA"},
    {"contest": "Masters World Championships - IFBB", "year": "2023",
     "date": "September 3, 2023", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Mr. & Ms. Lions Classic Grand Battle Pro - IFBB", "year": "2023",
     "date": "October 14, 2023", "location": "Guadalajara, Mexico"},
    {"contest": "San Antonio Pro - IFBB", "year": "2023",
     "date": "September 23, 2023", "location": "San Antonio, Texas, USA"},
    {"contest": "Sasquatch Pro - IFBB", "year": "2023",
     "date": "September 9, 2023", "location": "Federal Way, Washington, USA"},
    {"contest": "Sheru Classic France Pro - IFBB", "year": "2023",
     "date": "September 28-29, 2023", "location": "France"},
    {"contest": "Southern Muscle Showdown Pro - IFBB", "year": "2023",
     "date": "October 7, 2023", "location": "Dalton, Georgia, USA"},
    {"contest": "Ultimate Grand Prix Masters Pro - IFBB", "year": "2023",
     "date": "October 14, 2023", "location": "Boca Raton, Florida, USA"},
    {"contest": "Van City Showdown Pro - IFBB", "year": "2023",
     "date": "September 30, 2023", "location": "Burnaby, British Columbia, Canada"},
    {"contest": "MuscleContest Vietnam Pro - IFBB", "year": "2023",
     "date": "October 13, 2023", "location": "Vietnam"},
]

_page17 = [
    # Page 17
    {"contest": "Shawn Ray Hawaiian Classic Pro - IFBB", "year": "2023",
     "date": "November 18, 2023", "location": "Honolulu, Hawaii, USA"},
    {"contest": "Sheru Classic India Pro - IFBB", "year": "2023",
     "date": "November 17-19, 2023", "location": "Mumbai, India"},
    {"contest": "Romania Muscle Fest Pro - IFBB", "year": "2023",
     "date": "November 11, 2023", "location": "Bucharest, Romania"},
    {"contest": "Korea Pro - IFBB", "year": "2023",
     "date": "November 11, 2023", "location": "South Korea"},
    {"contest": "Caribbean Grand Prix Masters Pro - IFBB", "year": "2023",
     "date": "November 11, 2023", "location": "Nassau, Bahamas"},
    {"contest": "Texas State Pro - IFBB", "year": "2023",
     "date": "November 11, 2023", "location": "San Marcos, Texas, USA"},
    {"contest": "Hurricane Pro - IFBB", "year": "2023",
     "date": "October 21, 2023", "location": "St. Petersburg, Florida, USA"},
    {"contest": "Chattanooga Night of Champions Pro - IFBB", "year": "2023",
     "date": "October 21, 2023", "location": "Chattanooga, Tennessee, USA"},
    {"contest": "British Championships Pro - IFBB", "year": "2023",
     "date": "October 14, 2023", "location": "Manchester, United Kingdom"},
]

_page16 = [
    # Page 16
    {"contest": "Taiwan Pro - IFBB", "year": "2024",
     "date": "April 4, 2024", "location": "Kaohsiung, Taiwan"},
    {"contest": "Houston Tournament of Champions Pro - IFBB", "year": "2024",
     "date": "March 30, 2024", "location": "The Woodlands, Texas, USA"},
    {"contest": "Klash Series Championships Pro - IFBB", "year": "2024",
     "date": "March 30, 2024", "location": "Orlando, Florida, USA"},
    {"contest": "San Diego Pro - IFBB", "year": "2024",
     "date": "March 30, 2024", "location": "San Diego, California, USA"},
    {"contest": "Sampson Showdown Pro - IFBB", "year": "2024",
     "date": "March 23, 2024", "location": "Las Vegas, Nevada, USA"},
    {"contest": "MuscleContest Campinas Pro - IFBB", "year": "2024",
     "date": "March 16, 2024", "location": "Campinas, Brazil"},
    {"contest": "National Championships - NPC", "year": "2023",
     "date": "December 9, 2023"},
    {"contest": "Pharlabs Battle of Bogota Pro - IFBB", "year": "2023",
     "date": "November 18-19, 2023", "location": "Bogota, Colombia"},
]

_page15 = [
    # Page 15
    {"contest": "Los Angeles Grand Prix Pro - IFBB", "year": "2024",
     "date": "April 27, 2024", "location": "Anaheim, California, USA"},
    {"contest": "St. Louis Pro - IFBB", "year": "2024",
     "date": "April 27, 2024", "location": "St. Louis, Missouri, USA"},
    {"contest": "Klash Series GRL PWR Pro - IFBB", "year": "2024",
     "date": "April 27, 2024", "location": "Orlando, Florida, USA"},
    {"contest": "Emerald Cup Pro - IFBB", "year": "2024",
     "date": "April 26, 2024", "location": "Bellevue, Washington, USA"},
    {"contest": "Vancouver Island Showdown Pro - IFBB", "year": "2024",
     "date": "April 20, 2024", "location": "Victoria, British Columbia, Canada"},
    {"contest": "Wasatch Warrior Pro - IFBB", "year": "2024",
     "date": "April 20, 2024", "location": "Salt Lake City, Utah, USA"},
    {"contest": "Detroit Pro - IFBB", "year": "2024",
     "date": "April 13, 2024", "location": "Dearborn, Michigan, USA"},
    {"contest": "Tri-City Pro - IFBB", "year": "2024",
     "date": "April 13, 2024", "location": "Columbus, Georgia, USA"},
    {"contest": "Fitworld Pro - IFBB", "year": "2024",
     "date": "April 13, 2024", "location": "Los Angeles, California, USA"},
    {"contest": "Charlotte Cup Pro - IFBB", "year": "2024",
     "date": "April 6, 2024", "location": "Charlotte, North Carolina, USA"},
    {"contest": "Arnold Brazil Pro - IFBB", "year": "2024",
     "date": "April 5, 2024", "location": "Sao Paulo, Brazil"},
    {"contest": "1 Bro Pro Show - IFBB", "year": "2024",
     "date": "April 6, 2024", "location": "London, United Kingdom"},
    {"contest": "Triple O Dynasty Pro - IFBB", "year": "2024",
     "date": "April 6, 2024", "location": "Mesa, Arizona, USA"},
]

_page14 = [
    # Page 14
    {"contest": "German Classic Pro - IFBB", "year": "2024",
     "date": "May 25, 2024", "location": "St. Leon-Rot, Germany"},
    {"contest": "Optimum Classic Pro - IFBB", "year": "2024",
     "date": "May 25, 2024", "location": "Shreveport, Louisiana, USA"},
    {"contest": "California State Pro - IFBB", "year": "2024",
     "date": "May 25, 2024", "location": "Anaheim, California, USA"},
    {"contest": "Klash Series Southern USA Pro - IFBB", "year": "2024",
     "date": "May 25, 2024", "location": "Orlando, Florida, USA"},
    {"contest": "Mexico Pro - IFBB", "year": "2024",
     "date": "May 18, 2024", "location": "Guadalajara, Mexico"},
    {"contest": "New York Pro Championships - IFBB", "year": "2024",
     "date": "May 18, 2024", "location": "Teaneck, New Jersey, USA"},
    {"contest": "Junior USA Championships - NPC", "year": "2024",
     "date": "May 17, 2024"},
    {"contest": "Pittsburgh Pro - IFBB", "year": "2024",
     "date": "May 10, 2024", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Hungary Kokeny Pro - IFBB", "year": "2024",
     "date": "May 11, 2024", "location": "Budapest, Hungary"},
    {"contest": "AGP Bikini Pro - IFBB", "year": "2024",
     "date": "May 4, 2024", "location": "Paju City, South Korea"},
    {"contest": "AGP Pro - IFBB", "year": "2024",
     "date": "April 28, 2024", "location": "Gyeonggi, South Korea"},
    {"contest": "Dragon Physique DMS Pro - IFBB", "year": "2024",
     "date": "April 28, 2024", "location": "Changsha, China"},
]

_page13 = [
    # Page 13
    {"contest": "South Florida Pro - IFBB", "year": "2024",
     "date": "June 22, 2024", "location": "Boca Raton, Florida, USA"},
    {"contest": "Empro Pro - IFBB", "year": "2024",
     "date": "June 16, 2024", "location": "Alicante, Spain"},
    {"contest": "Dallas Pro - IFBB", "year": "2024",
     "date": "June 15, 2024", "location": "Dallas, Texas, USA"},
    {"contest": "Southern California Championships Pro - IFBB", "year": "2024",
     "date": "June 15, 2024", "location": "San Diego, California, USA"},
    {"contest": "Toronto Pro Supershow - IFBB", "year": "2024",
     "date": "June 9, 2024", "location": "Toronto, Ontario, Canada"},
    {"contest": "Oklahoma Pro - IFBB", "year": "2024",
     "date": "June 8, 2024", "location": "Tulsa, Oklahoma, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2024",
     "date": "June 8, 2024", "location": "Omaha, Nebraska, USA"},
    {"contest": "DC Pro - IFBB", "year": "2024",
     "date": "June 8, 2024", "location": "Alexandria, Virginia, USA"},
    {"contest": "Adela Garcia Pro - IFBB", "year": "2024",
     "date": "June 8, 2024", "location": "Bastrop, Texas, USA"},
    {"contest": "Mile High Pro - IFBB", "year": "2024",
     "date": "June 8, 2024", "location": "Denver, Colorado, USA"},
    {"contest": "Mid-USA Pro - IFBB", "year": "2024",
     "date": "June 2, 2024", "location": "Albuquerque, New Mexico, USA"},
    {"contest": "Miami Muscle Beach Pro - IFBB", "year": "2024",
     "date": "June 1, 2024", "location": "Miami, Florida, USA"},
    {"contest": "Nevada State Pro - IFBB", "year": "2024",
     "date": "June 1, 2024", "location": "Las Vegas, Nevada, USA"},
]

_page11 = [
    # Page 11
    {"contest": "Tampa Pro - IFBB", "year": "2024",
     "date": "August 1, 2024", "location": "Tampa, Florida, USA"},
    {"contest": "Dubai Pro - IFBB", "year": "2024",
     "date": "July 28, 2024", "location": "Dubai, United Arab Emirates"},
    {"contest": "USA Championships - NPC", "year": "2024",
     "date": "July 26-27, 2024"},
    {"contest": "Colombia Pro - IFBB", "year": "2024",
     "date": "July 18, 2024", "location": "Medellin, Colombia"},
    {"contest": "Teen Collegiate & Masters National Championships - NPC", "year": "2024",
     "date": "July 17-18, 2024"},
    {"contest": "Patriots Challenge Pro - IFBB", "year": "2024",
     "date": "July 20, 2024", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Vancouver Pro - IFBB", "year": "2024",
     "date": "July 13, 2024", "location": "Abbotsford, British Columbia, Canada"},
    {"contest": "Lenda Murray Atlanta Pro - IFBB", "year": "2024",
     "date": "July 13, 2024", "location": "Atlanta, Georgia, USA"},
    {"contest": "Zhanna Rotar Los Angeles Pro - IFBB", "year": "2024",
     "date": "July 13, 2024", "location": "Anaheim, California, USA"},
    {"contest": "Republic of Texas Pro - IFBB", "year": "2024",
     "date": "July 13, 2024", "location": "Austin, Texas, USA"},
]

_page10 = [
    # Page 10
    {"contest": "Arizona Pro - IFBB", "year": "2024",
     "date": "August 24, 2024", "location": "Phoenix, Arizona, USA"},
    {"contest": "Rising Phoenix Pro - IFBB", "year": "2024",
     "date": "August 24, 2024", "location": "Phoenix, Arizona, USA"},
    {"contest": "World Klash Pro - IFBB", "year": "2024",
     "date": "August 24, 2024", "location": "Charleston, South Carolina, USA"},
    {"contest": "Tupelo Pro - IFBB", "year": "2024",
     "date": "August 16, 2024", "location": "Tupelo, Mississippi, USA"},
    {"contest": "Florida State Pro - IFBB", "year": "2024",
     "date": "August 10, 2024", "location": "Orlando, Florida, USA"},
    {"contest": "Pacific USA Pro - IFBB", "year": "2024",
     "date": "August 10, 2024", "location": "San Diego, California, USA"},
]

_page9 = [
    # Page 9
    {"contest": "Daytona Pro - IFBB", "year": "2024",
     "date": "September 28, 2024", "location": "Daytona Beach, Florida, USA"},
    {"contest": "Titans Grand Prix Pro - IFBB", "year": "2024",
     "date": "September 21, 2024", "location": "Anaheim, California, USA"},
    {"contest": "Turkiye Pro - IFBB", "year": "2024",
     "date": "September 19, 2024", "location": "Izmir, Turkey"},
    {"contest": "Europa Pro - IFBB", "year": "2024",
     "date": "September 14, 2024", "location": "London, United Kingdom"},
    {"contest": "Battle of the Bodies Pro - IFBB", "year": "2024",
     "date": "September 14, 2024", "location": "Ft. Lauderdale, Florida, USA"},
    {"contest": "San Antonio Pro - IFBB", "year": "2024",
     "date": "September 14, 2024", "location": "San Antonio, Texas, USA"},
    {"contest": "Pro Muscle Pro - IFBB", "year": "2024",
     "date": "September 8, 2024", "location": "Milan, Italy"},
    {"contest": "Florida Pro - IFBB", "year": "2024",
     "date": "September 7, 2024", "location": "Sarasota, Florida, USA"},
    {"contest": "Heart of Texas Pro - IFBB", "year": "2024",
     "date": "September 7, 2024", "location": "Dallas, Texas, USA"},
    {"contest": "RGV Classic Pro - IFBB", "year": "2024",
     "date": "August 31, 2024", "location": "McAllen, Texas, USA"},
    {"contest": "Masters World Championships - IFBB", "year": "2024",
     "date": "September 1, 2024", "location": "Pittsburgh, Pennsylvania, USA"},
]

_page7 = [
    # Page 7
    {"contest": "Pittsburgh Power & Fitness Pro - IFBB", "year": "2025",
     "date": "May 10, 2025", "location": "Pittsburgh, Pennsylvania, USA"},
    {"contest": "Los Angeles Grand Prix Pro - IFBB", "year": "2025",
     "date": "April 26, 2025", "location": "Anaheim, California, USA"},
    {"contest": "GRL PWR Pro - IFBB", "year": "2025",
     "date": "April 26, 2025", "location": "Orlando, Florida, USA"},
    {"contest": "Huanji China Pro - IFBB", "year": "2025",
     "date": "April 20, 2025", "location": "Shanghai, China"},
    {"contest": "St. Louis Pro - IFBB", "year": "2025",
     "date": "April 19, 2025", "location": "St. Louis, Missouri, USA"},
    {"contest": "1 Bro Pro Show - IFBB", "year": "2025",
     "date": "April 19, 2025", "location": "Maidenhead, United Kingdom"},
    {"contest": "FIBO Pro Championships - IFBB", "year": "2025",
     "date": "April 12, 2025", "location": "Cologne, Germany"},
    {"contest": "Charlotte Cup Pro - IFBB", "year": "2025",
     "date": "April 12, 2025", "location": "Charlotte, North Carolina, USA"},
    {"contest": "Detroit Pro - IFBB", "year": "2025",
     "date": "March 29, 2025", "location": "Dearborn, Michigan, USA"},
    {"contest": "Sampson Showdown Pro - IFBB", "year": "2025",
     "date": "March 29, 2025", "location": "Las Vegas, Nevada, USA"},
    {"contest": "San Diego Pro - IFBB", "year": "2025",
     "date": "March 8, 2025", "location": "San Diego, California, USA"},
    {"contest": "Arnold Classic - IFBB", "year": "2025",
     "date": "February 28 - March 1, 2025", "location": "Columbus, Ohio, USA"},
]

_page8 = [
    # Page 8
    {"contest": "Bharat Pro Show - IFBB", "year": "2024",
     "date": "December 20, 2024", "location": "Mumbai, India"},
    {"contest": "Japan Pro - IFBB", "year": "2024",
     "date": "November 24, 2024", "location": "Tokyo, Japan"},
    {"contest": "Kansas City Pro - IFBB", "year": "2024",
     "date": "November 23, 2024", "location": "Kansas City, Missouri, USA"},
    {"contest": "EVLS Prague Pro - IFBB", "year": "2024",
     "date": "November 16, 2024", "location": "Prague, Czech Republic"},
    {"contest": "Ben Weider Natural Pro - IFBB", "year": "2024",
     "date": "November 15, 2024", "location": "Alexandria, Virginia, USA"},
    {"contest": "Atlantic Coast Pro - IFBB", "year": "2024",
     "date": "November 16, 2024", "location": "Ft. Lauderdale, Florida, USA"},
    {"contest": "Texas State Pro - IFBB", "year": "2024",
     "date": "November 9, 2024", "location": "San Marcos, Texas, USA"},
    {"contest": "Olympia - IFBB", "year": "2024",
     "date": "October 11-12, 2024", "location": "Las Vegas, Nevada, USA"},
    {"contest": "Legion Pro - IFBB", "year": "2024",
     "date": "September 29, 2024", "location": "Reno, Nevada, USA"},
]

# Page 6 (kept for reference)
_page6 = [
    # Page 6
    {"contest": "Spanish Masters Pro - IFBB", "year": "2025",
     "date": "June 8, 2025", "location": "Madrid, Spain"},
    {"contest": "Adela Garcia Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Austin, Texas, USA"},
    {"contest": "Oklahoma Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Tulsa, Oklahoma, USA"},
    {"contest": "DC Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Manassas, Virginia, USA"},
    {"contest": "Mile High Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Denver, Colorado, USA"},
    {"contest": "Southern California Championships Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "San Diego, California, USA"},
    {"contest": "Omaha Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Omaha, Nebraska, USA"},
    {"contest": "Thailand Pro - IFBB", "year": "2025",
     "date": "June 7, 2025", "location": "Pattaya, Thailand"},
    {"contest": "Legion Sports Fest Pro - IFBB", "year": "2025",
     "date": "May 31, 2025", "location": "Reno, Nevada, USA"},
    {"contest": "Miami Pro - IFBB", "year": "2025",
     "date": "May 24, 2025", "location": "Miami, Florida, USA"},
    {"contest": "California State Pro - IFBB", "year": "2025",
     "date": "May 24, 2025", "location": "Anaheim, California, USA"},
    {"contest": "New York Pro Championships - IFBB", "year": "2025",
     "date": "May 17, 2025", "location": "Teaneck, New Jersey, USA"},
    {"contest": "Pittsburgh Natural Pro Qualifier - NPC Worldwide", "year": "2025",
     "date": "May 10, 2025"},
]

# Build lookup: contest name (lowered) -> index in data
index = {e["contest"].lower(): i for i, e in enumerate(data)}

added = []
skipped = []
conflicts = []

for entry in new_entries:
    name = entry["contest"]
    year = entry["year"]
    year_data = {k: v for k, v in entry.items() if k not in ("contest", "year") and v}

    idx = index.get(name.lower())
    if idx is not None:
        # Contest exists — check if this year already has data
        existing_year = data[idx]["years"].get(year)
        if existing_year:
            # Compare non-empty fields for conflicts
            diff = {k: (existing_year.get(k), v)
                    for k, v in year_data.items()
                    if existing_year.get(k) and existing_year.get(k) != v}
            if diff:
                conflicts.append(f"CONFLICT: \"{data[idx]['contest']}\" {year} — stored: {existing_year}, extracted: {year_data}")
            else:
                # Fill in any empty fields with new values
                updated = False
                for k, v in year_data.items():
                    if not data[idx]["years"][year].get(k):
                        data[idx]["years"][year][k] = v
                        updated = True
                if updated:
                    added.append(f"UPDATED year {year} in existing \"{data[idx]['contest']}\"")
                else:
                    skipped.append(f"SKIP (matches): \"{data[idx]['contest']}\" {year}")
        else:
            data[idx]["years"][year] = year_data
            added.append(f"ADDED year {year} to existing \"{data[idx]['contest']}\"")
    else:
        # New contest entirely
        data.append({"contest": name, "years": {year: year_data}})
        index[name.lower()] = len(data) - 1
        added.append(f"ADDED new contest \"{name}\" {year}")

with open(path, "w") as f:
    json.dump(data, f, indent=2)

print("\n".join(added))
if skipped:
    print("\n".join(skipped))
if conflicts:
    print("\n".join(conflicts))
print(f"\nDone: {len(added)} added, {len(skipped)} skipped, {len(conflicts)} conflicts")
